<a href="https://colab.research.google.com/github/pranavkagrawal02/Minor-In-AI-IIT-Ropar/blob/main/Feb_20_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list1 = [1,2,3,4,5]

In [ ]:
print(list1)

[1, 2, 3, 4, 5]


In [ ]:
print(list1[3])

4


In [ ]:
list1 = [1, 'Kartik', 1.2, True] #Can contain different types

In [ ]:
len(list1)

4

In [ ]:
# Machine Learning - Large Dataset (Numbers)
# Lists -> Slow, Computationally Expensive

In [ ]:
# Numeric Python -> Numpy
# Numpy Arrays -> List -> Collection of objects
# +faster +powerful
# - Store same datatypes

In [ ]:
import numpy as np
np1 = np.array([1,2,3,4,5])

In [ ]:
print(np1)
print(np1[3])

[1 2 3 4 5]
4


In [ ]:
np1.shape

(5,)

In [ ]:
#List should contain numbers from 0 to 9b--> For loop

In [ ]:
np2 = np.arange(0,10)

In [ ]:
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 2 4 6 8 10 12 14 16

In [ ]:
np3 = np.array([2,4,6,8])

In [ ]:
np3 = np.arange(2,20,2)

In [ ]:
print(np3)

[ 2  4  6  8 10 12 14 16 18]


In [ ]:
np4 = np.arange(20,10,-3)
print(np4)

[20 17 14 11]


In [ ]:
0 0 0 0 0 0 0 0 0

In [ ]:
np5 = np.ones(10)
print(np5)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
np5.shape

(10,)

In [ ]:
np6 = np.array([ [1,1,1,1,1]
                 [1,1,1,1,1]
                 [1,1,1,1,1]
                    ])

In [ ]:
#Numpy Functions
np7 = [1,20,16,23,45,67,21,5]
np.min(np7)

1

In [ ]:
np.sqrt(np7)

array([1.        , 4.47213595, 4.        , 4.79583152, 6.70820393,
       8.18535277, 4.58257569, 2.23606798])

In [ ]:
np.mean(np7)

24.75

In [ ]:
np.sort(np7)

array([ 1,  5, 16, 20, 21, 23, 45, 67])

In [ ]:
np8 = ['Aman', 'harman', 'Shashank', 'Khusboo']
np.sort(np8)

array(['Aman', 'Khusboo', 'Shashank', 'harman'], dtype='<U8')

In [ ]:
np9 = np.array ([  ] [4,2,3],
                    [6,10,4] ])

In [ ]:
np.sort(np9)

array([[ 2,  3,  4],
       [ 4,  6, 10]])

In [ ]:
np10 = np.array([True, False, True, True, False])
np.sort(np10)

array([False, False,  True,  True,  True])

In [ ]:
np10 + 2

array([1, 2, 3, 4, 5])

In [ ]:
np10 ** 10

array([      1,    1024,   59049, 1048576, 9765625])

In [ ]:
np10 = np.array([1,2,3,4])
np11 = np.array([1,0,1,0])

In [ ]:
np10 == np11

array([ True, False, False, False])

In [ ]:
np12 = np.array([ [1,2,3],
                  [4,5,6],
                  [7,8,9]
                        ])

np13 = np.array([ [1,2,3],
                  [4,5,6],
                  [7,8,9]
                        ])

In [ ]:
np12*np13

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
#Matrix Multiplication
np12 @ np13

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
np12 = np.array([ [1,2,3],
                  [4,5,6],
                  [7,8,9]
                        ])
np13 = np.array([ [1,0,0],
                  [0,1,0],
                  [0,0,1]
                        ])
print(np13 * np12)
print(np13 @ np12)

[[1 0 0]
 [0 5 0]
 [0 0 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
np1 = np.array([3,4,5,6,7,8])

In [ ]:
np1[-3]

6

In [ ]:
# 0 1 2 3

In [ ]:
np1[0 : -1] # 2 3 4

array([3, 4, 5, 6, 7])

In [ ]:
np1[2:]

array([5, 6, 7, 8])

In [ ]:
np1[:5]

array([3, 4, 5, 6, 7])

In [ ]:
np1[:]

array([3, 4, 5, 6, 7, 8])

In [ ]:
np1 = np.array([3,4,5,6,7,8])
np1[0:-2:2]

array([3, 5])

In [ ]:
np1 [::2]

array([3, 5, 7])

In [ ]:
np2 = np.array([ [1,2,3,4,5,6,7], [8,9,10,11,12,13,14]   ])
print(np2)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
np2[:,2:5]

array([[ 3,  4,  5],
       [10, 11, 12]])

In [ ]:
np2

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
np2[1,4] = 20
print(np2)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 20 13 14]]


In [ ]:
np2[:, 1] = [20,30]
print(np2)

[[ 1 20  3  4  5  6  7]
 [ 8 30 10 11 20 13 14]]


In [ ]:
np2[0, :] = [1,1,1,1,1,1,1]
print(np2)

[[ 1  1  1  1  1  1  1]
 [ 8 30 10 11 20 13 14]]


In [ ]:
outer = np.ones((5,5))

In [ ]:
outer

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
inner = np.zeros((3,3))
inner

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
inner[1,1] = 9
inner

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [ ]:
outer[1:4, 1:4] = inner
outer

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#Reshaping
np2 = np.array([1,2,3,4,5,6,7,8])

In [ ]:
np2.shape

(6,)

In [ ]:
# (2,3)
np_2d = np2.reshape(2,-1,2)
print(np_2d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [10 16]
  [18 20]]]


In [ ]:
outer

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr = outer.reshape(25)
print(arr)

[1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0. 9. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1.
 1.]


In [ ]:
a = np.array([1,2,3,4,5])
b = a.copy()

In [ ]:
b[1] = 100
print(b)


[  1 100   3   4   5]


In [ ]:
print(a)

[1 2 3 4 5]
